title: Family Bake Club
description: Delicious family baking recipes
baseurl: "/FamilyBakeClub-Website"
url: "https://addisoneshinkle.github.io"

# Collections
collections:
  recipes:
    output: true
    permalink: /recipes/:name/

defaults:
  - scope:
      path: ""
      type: "recipes"
    values:
      layout: "recipe"

# Include data folder
include:
  - _data

# Markdown
markdown: kramdown
theme: minima
