title: Family Bake Club
description: Delicious family baking recipes
baseurl: "/FamilyBakeClub-Website"
url: "https://addisoneshinkle.github.io"

# Collections
collections:
    recipes:
        output: true
        permalink: /recipes/:name/

# Include data files if needed
include:
    - _data

# Markdown settings
markdown: kramdown
theme: minima

# Optional plugins if you want to auto-generate pages from JSON
plugins:
  - jekyll-datapage_gen

jekyll_datapage_gen:
  datafiles: ["_data/recipes/*.json"]
  template: "recipe"
  name: "recipe_name"
  dir: "recipes"
