title: Family Bake Club
description: Delicious family baking recipes
baseurl: "/FamilyBakeClub-Website"
url: "https://addisoneshinkle.github.io"

# Collections
collections:
  recipes:
    output: true
    permalink: /recipes/:name/

# Include data folder
include:
  - _data

# Markdown
markdown: kramdown
theme: minima
